server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice2
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka